.Dd January 12, 2010
.Os
.Dt testing 2
.Sh NAME
.Nm testing
.Nd testing man page
.Sh SYNOPSIS
.Nm
.Op Fl AZjkr0
.Op Fl verbose
.Op Fl silliness Ar n
.Op Fl input Ao input Ac
.Sh DESCRIPTION
.Pp
This is a small, temporary description of the testing man page. I'm going to fill in some totally
.Sy random
text here that nobody is
.Em ever
going to pay attention to! In fact, I think
.Sy this
is the dumbest paragraph
.Em ever
\&.
.Bl -tag -width 9n -compact
.Pp
.It Fl r
Some r flag
.Pp
.It Fl j
Some j flag
.Pp
.It Fl k
Some k flag
.Pp
.It Fl 0
Some zero flag
.Pp
.It Fl A
Some capitalized flag
.Pp
.It Fl Z
some big-z flag
.Pp
.It Fl verbose
The verbose flag does a lot of stuff.
.Pp
.It Fl silliness Ar n
Set how silly the application should be.
.Pp
.It Fl input Ao input Ac
The input flag takes a filename
.El
.Pp
.Sh SEE ALSO
.Xr ruby
.Xr rails 1
.Sh HISTORY
.Pp
This program has a storied history that I am too lazy to include here.
.Sh AUTHORS
.An "Michael Edgar" Aq adgar@carboni.ca
.Sh BUGS
.Pp
There are a few bugs, but nothing too serious.
