# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rtfm}
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Edgar"]
  s.date = %q{2010-01-10}
  s.description = %q{Using RTFM, you can declaratively create nice, standard man pages for your 
Ruby projects using a slick, maintainable DSL. It also includes rake tasks 
to aid in debugging, generating, and installing your man files.
}
  s.email = %q{michael.j.edgar@dartmouth.edu}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/rtfm.rb",
     "lib/rtfm/groffstring.rb",
     "lib/rtfm/manpage.rb",
     "lib/rtfm/option.rb",
     "lib/rtfm/sections/authors.rb",
     "lib/rtfm/sections/description.rb",
     "lib/rtfm/sections/see_also.rb",
     "lib/rtfm/sections/synopsis.rb",
     "lib/rtfm/sections/text.rb",
     "lib/rtfm/tasks.rb",
     "lib/rubygems_plugin.rb",
     "man/testing.2",
     "spec/authors_spec.rb",
     "spec/description_spec.rb",
     "spec/groffstring_spec.rb",
     "spec/rtfm_spec.rb",
     "spec/see_also_spec.rb",
     "spec/spec_helper.rb",
     "spec/synopsis_spec.rb"
  ]
  s.homepage = %q{http://github.com/michaeledgar/rtfm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Create makefiles declaratively. Comes with rake tasks.}
  s.test_files = [
    "spec/authors_spec.rb",
     "spec/description_spec.rb",
     "spec/groffstring_spec.rb",
     "spec/rtfm_spec.rb",
     "spec/see_also_spec.rb",
     "spec/spec_helper.rb",
     "spec/synopsis_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bacon>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<bacon>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<bacon>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end
