.Dd January 08, 2010
.Os
.Dt testing 2
.Sh NAME
.Nm testing
.Nd testing man page
.Sh SYNOPSIS

.Sh DESCRIPTION
This is a small, temporary description of the testing man page.
.Bl -tag -width "mmmmmmmmmm" -compact
.Pp
.It Fl verbose
The verbose flag does a lot of stuff.
.Pp
.It Fl input Ao input Ac
The input flag takes a filename
.El
.Pp
.Sh SEE ALSO
.Xr ruby
.Xr rails 1
.Sh HISTORY
This program has a storied history that I am too lazy to include here.
.Sh AUTHORS
.An "Michael Edgar" Aq adgar@carboni.ca
.Sh BUGS
There are a few bugs, but nothing too serious.
